[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-toml" },
  { id = "check-json" },
  { id = "check-yaml" },
  { id = "check-added-large-files", args = ["--maxkb=1024"] },
  { id = "check-merge-conflict" },
  { id = "check-case-conflict" },
  { id = "check-symlinks" },
  { id = "mixed-line-ending" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "stylua"
name = "stylua"
language = "system"
entry = "stylua --check"
files = '\.luau$'
exclude = '\.d\.luau$'

[[repos.hooks]]
id = "luau-analyze"
name = "luau-analyze"
language = "system"
entry = "luau-lsp analyze --definitions=noctalia.d.luau --base-luaurc=.luaurc"
files = '\.luau$'
exclude = '\.d\.luau$'

[[repos.hooks]]
id = "noctalia-validate"
name = "noctalia-validate"
language = "system"
entry = "./validate.sh"
pass_filenames = false
always_run = true

[[repos.hooks]]
id = "shellcheck"
name = "shellcheck"
language = "system"
entry = "shellcheck"
files = '\.sh$'

[[repos.hooks]]
id = "nixfmt"
name = "nixfmt"
language = "system"
entry = "nixfmt --check"
files = '\.nix$'

[[repos.hooks]]
id = "zizmor"
name = "zizmor"
language = "system"
entry = "zizmor --no-progress --persona=pedantic"
files = '^\.github/workflows/'
