name: ci

on:
  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}

permissions: {}

jobs:
  prek:
    name: prek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
        with:
          enable-cache: false
      - run: |
          mkdir -p "$HOME/.local/bin"
          curl -sSLo stylua.zip https://github.com/JohnnyMorganz/StyLua/releases/download/v2.5.2/stylua-linux-x86_64.zip
          unzip -q stylua.zip -d "$HOME/.local/bin"
          chmod +x "$HOME/.local/bin/stylua"
          uvx prek run --all-files
